### ISSUE TITLE
SSL issue on mac

### ISSUE THREAD

**Issue by alairock** [pyslackers/sirbot-slack#15]
On a mac, you might get an issue with SSL Certs on mac with Python 3.6. 

The solution to this is  navigate to  `/Applications/Python 3.6/` folder and double click the Install Certificates.command.

Problem solved.

**Comment by alairock** [comment]
Leaving this here for historical purposes. In case someone else runs into it.

**Comment by mattrasband** [comment]
Good comment :)

For more context:

> In it, the section on "Certificate verification and OpenSSL" notes that, as of the 3.6.0 installer, the Python supplied no longer links with the deprecated Apple-supplied system OpenSSL libraries but rather supplies a private copy of OpenSSL 1.0.2 which does not automatically access the system default root certificates.  "For 3.6.0, a sample command script is included in /Applications/Python 3.6 to install a curated bundle of default root certificates from the third-party certifi package (https://pypi.python.org/pypi/certifi).

From [https://bugs.python.org/issue29065](https://bugs.python.org/issue29065)
