### ISSUE TITLE
Add cancel button to `/gif` previews

### ISSUE THREAD

**Issue by autoferrit** [pyslackers/sirbot-slack#47]
When searching for a gif, we should add a cancel button so we dont have to try and manually delete the message in case we decide not to post a gif

![image](https://user-images.githubusercontent.com/89895/28351000-de1606b8-6c01-11e7-8d8b-04bcdbdff478.png)

Buttons: [Send] [Previous] [Next] [Cancel]

**Comment by ovv** [comment]
This types of issues should go in pyslackers/sirbot-pythondev#62
